services:
  - type: web
    name: telegram-session-generator
    env: node
    plan: free
    buildCommand: npm install && pip install -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
